[package]
name = "check_mate_server"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
check_mate_common = { version = "0.3.0", path = "../common" }
tokio = { version = "1", features = ["full"] }
